# Railway Deployment Configuration
# https://docs.railway.app/deploy/railway-toml-file

[build]
  # Use package.json scripts for building
  builder = "NIXPACKS"

[deploy]
  # Run migrations before starting the server
  # Railway will run this command on every deploy
  startCommand = "bash start.sh"
  
  # Restart policy
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  # Environment variables are managed in Railway dashboard




